/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.std;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.net.Socket;
import java.util.Scanner;

public class App {


    public static void main(String[] args) {

        String servidor = args[0];
//        String servidor = "LocalHost";
//        int porta = 1234;


        int porta = Integer.parseInt(args[1]);

        try(Socket socket = new Socket(servidor, porta)){

            System.out.println("Conectado no servidor...");

            //Fluxos de I/O
            BufferedReader entrada = new BufferedReader(new InputStreamReader(socket.getInputStream()));

            OutputStreamWriter saida = new OutputStreamWriter(socket.getOutputStream(), "UTF-8");

            Scanner sc = new Scanner(System.in);


            while (true) {

                System.out.print(">");
                String mensagem = sc.nextLine();
                saida.write(mensagem + "\n");
                saida.flush();

                if (mensagem.equals("fim")){
                    break;
                }
                String resposta = entrada.readLine();

                System.out.println("resposta: " + resposta);

            }

        } catch (Exception e) {
            System.out.println("Erro: "+e.toString());
        }

        System.out.println("Desconectado do servidor...");


    }
}
