/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.std;

import java.io.*;
import java.net.Socket;
import java.util.Scanner;

public class App {


    public static void main(String[] args) {

        String servidor = "LocalHost";
        int porta = 1234;

//        String servidor = args[0];
//        int porta = Integer.parseInt(args[1]);

        try(Socket socket = new Socket(servidor, porta)){

            System.out.println("Conectado no servidor...");



            Scanner sc = new Scanner(System.in);
            System.out.print("Nome do arquivo>");
            String nomeArquivo = sc.nextLine();


            // DataInputStream
            DataOutputStream dos = new DataOutputStream(socket.getOutputStream());
            DataInputStream dis = new DataInputStream(socket.getInputStream());
            dos.writeUTF(nomeArquivo);

            long tamanhoArquivo = dis.readLong();

            FileOutputStream fos = new FileOutputStream(nomeArquivo);
            byte[] buffer = new byte[4096];
            long total = 0;
            int bytesLidos;

            while (total < tamanhoArquivo && (bytesLidos = dis.read(buffer, 0, (int)Math.min(buffer.length,
                    tamanhoArquivo - total))) != -1) {

                fos.write(buffer, 0, bytesLidos);

                total += bytesLidos;
                System.out.println("bites lidos: " +  total);
            }

            fos.close();
            dis.close();

        } catch (Exception e) {
            System.out.println("Erro: "+e.toString());
        }

        System.out.println("Desconectado do servidor...");


    }
}
